// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWuqAB_l78FpyRbnkxcf1YnBZ3mNfETlM',
    appId: '1:613670630772:web:579c2fbfeed8254cef2821',
    messagingSenderId: '613670630772',
    projectId: 'gkias-website-db',
    authDomain: 'gkias-website-db.firebaseapp.com',
    storageBucket: 'gkias-website-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoNT0ZjhxneAcwSb8pMdtGBW2sEFFBjZA',
    appId: '1:613670630772:android:28a6e5b754fce0e7ef2821',
    messagingSenderId: '613670630772',
    projectId: 'gkias-website-db',
    storageBucket: 'gkias-website-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeOJjCA27hYQZYk29FExs8qn3agKMRZ2U',
    appId: '1:613670630772:ios:d5e24b2c5762d5f1ef2821',
    messagingSenderId: '613670630772',
    projectId: 'gkias-website-db',
    storageBucket: 'gkias-website-db.firebasestorage.app',
    iosBundleId: 'com.example.gkiasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeOJjCA27hYQZYk29FExs8qn3agKMRZ2U',
    appId: '1:613670630772:ios:d5e24b2c5762d5f1ef2821',
    messagingSenderId: '613670630772',
    projectId: 'gkias-website-db',
    storageBucket: 'gkias-website-db.firebasestorage.app',
    iosBundleId: 'com.example.gkiasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWuqAB_l78FpyRbnkxcf1YnBZ3mNfETlM',
    appId: '1:613670630772:web:579c2fbfeed8254cef2821',
    messagingSenderId: '613670630772',
    projectId: 'gkias-website-db',
    authDomain: 'gkias-website-db.firebaseapp.com',
    storageBucket: 'gkias-website-db.firebasestorage.app',
  );

}